# Generated by Django 4.2.13 on 2024-07-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('AD', 'admin'), ('LN', 'learner'), ('HO', 'host')], default='LN', max_length=10),
        ),
    ]
