# Generated by Django 4.1.5 on 2024-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.TextField(
                choices=[("AD", "admin"), ("HO", "host"), ("LN", "learner")],
                default="LN",
                max_length=10,
            ),
        ),
    ]
