# Generated by Django 5.0.7 on 2024-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('HO', 'host'), ('LN', 'learner'), ('AD', 'admin')], default='LN', max_length=10),
        ),
    ]
