# Generated by Django 5.0.7 on 2024-08-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_birthday'),
        ('account', '0011_alter_profile_role'),
    ]

    operations = [
    ]
