# Generated by Django 5.0.7 on 2024-08-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('HO', 'host'), ('AD', 'admin'), ('LN', 'learner')], default='LN', max_length=10),
        ),
    ]
