# Generated by Django 4.1.5 on 2024-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="roomPrivacy",
            field=models.CharField(
                choices=[("PB", "public"), ("PR", "private")],
                default="PB",
                max_length=10,
            ),
        ),
    ]
