# Generated by Django 5.0.7 on 2024-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_roomprivacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomPrivacy',
            field=models.CharField(choices=[('PR', 'private'), ('PB', 'public')], default='PB', max_length=10),
        ),
    ]
