# Generated by Django 5.0.7 on 2024-08-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_roomprivacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
