# Generated by Django 3.2.12 on 2024-08-23 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_token',
            field=models.CharField(blank=True, default=uuid.UUID('d173770e-97e8-4d47-bc02-48226b811bc8'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
