# Generated by Django 5.0.7 on 2024-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20240823_0327'),
        ('room', '0009_remove_room_invite_token'),
    ]

    operations = [
    ]
