# Generated by Django 5.0.7 on 2024-08-29 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_remove_tracking_time_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_time',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
