# Generated by Django 5.0.7 on 2024-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_merge_20240828_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='invite_token',
        ),
    ]
