# Generated by Django 3.2.20 on 2024-08-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_tracking_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_time',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
