# Generated by Django 5.0.7 on 2024-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_remove_room_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_token',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
