# Generated by Django 3.2.20 on 2024-08-29 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_tracking_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_time',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
