# Generated by Django 3.2.20 on 2024-08-29 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_alter_tracking_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 12, 50, 54, 537205, tzinfo=utc)),
        ),
    ]
