# Generated by Django 5.0.7 on 2024-08-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_profile_role'),
        ('room', '0014_alter_image_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomHost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to='account.profile'),
        ),
    ]
