# Generated by Django 3.2.20 on 2024-08-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_traceactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='traceActivity',
        ),
    ]
